### ISSUE TITLE
ImportError: No module named callbacks

### ISSUE THREAD

**Issue by tkald** [modoboa/modoboa-pfxadmin-migrate#12]
Getting error when running migrate_from_postfixadmin command:

```python
python manage.py migrate_from_postfixadmin -s plain
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 45, in <module>
    from modoboa.admin.callbacks import grant_access_to_all_objects
ImportError: No module named callbacks
```

**Comment by tonioo** [comment]
@tkald Are you sure you're using the latest version?

**Comment by tkald** [comment]
I see, pip install gave me a 1.0.3 version.

**Comment by tonioo** [comment]
Ok, so please install 1.1.0 version.

**Comment by tkald** [comment]
Pip install doesn't seem to find 1.1.0 version:

> pip install modoboa-pfxadmin-migrate==1.1.0
> Collecting modoboa-pfxadmin-migrate==1.1.0
>   Could not find a version that satisfies the requirement modoboa-pfxadmin-migrate==1.1.0 (from versions: 1.0.1, 1.0.2, 1.0.3)
> No matching distribution found for modoboa-pfxadmin-migrate==1.1.0

**Comment by tonioo** [comment]
My bad, I forgot to upload the package on Pypi :p

**Comment by tkald** [comment]
With 1.1.0 version I now get following error:

> Migrating domain mydomain.name
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 294, in handle
    self._do_migration(options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 286, in _do_migration
    self._migrate_domain(pf_domain, options, creator)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 200, in _migrate_domain
    newdom.dates = self._migrate_dates(pf_domain)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 94, in _migrate_dates
    dates = admin_models.base.ObjectDates()
AttributeError: 'module' object has no attribute 'ObjectDates'

Modoboa 1.7.1

**Comment by tonioo** [comment]
@tkald I just pushed a fix, could you try it?

**Comment by tkald** [comment]
Works for me. Thanks!
