### ISSUE TITLE
Script Failure on Ubuntu 20.04 LTS New Modoboa Install

### ISSUE THREAD

**Issue by rjbutler3** [modoboa/modoboa-pfxadmin-migrate#20]
I was asked several months ago to evaluate email solutions for a small local company.  After evaluating several options, I settled on Modoboa as a replacement for their current Postfix/Dovecot system.  It took a lot of convincing.  The most important issue for them was whether I could migrate their current email accounts and mail to Modoboa.  I understand that there are two scripts, modoboa-pfxadmin-migrate and modoboa-imap-migration.  I chose to use modoboa-pfxadmin-migrate.  I followed the instructions for installation and usage.  I immediately encountered errors.

Ubuntu 20.04 LTS uses Python3.  The command "python" is aliased to "python3"

Upon executing the script, I received the following errors;

root@sensa-mx-1:/srv/modoboa/instance# python manage.py migrate_from_postfixadmin -s crypt
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'migrate_from_postfixadmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/instance/instance/settings.py", line 372, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
ModuleNotFoundError: No module named 'modoboa_amavis'

**Comment by tonioo** [comment]
@rjbutler3 Stupid question; have you added the   'modoboa_pfxadmin_migrate' app to the INSTALLED_APPS setting?

**Comment by rjbutler3** [comment]
Good Day Antoine,

There are no "stupid questions".

I followed the directions found here;
https://github.com/modoboa/modoboa-pfxadmin-migrate
I then ran pylint settings.py to insure that my edits were syntactically correct.
I then ran the command;

python manage.py migrate_from_postfixadmin -s crypt

Just had a thought.  Modoboa was installed using the modoboa-installer.  Do I need to activate the python virtual environment before running modoboa-pfxadmin-migrate?  In other words, do I have to execute /srv/modoboa/env/bin/activate first?

**Comment by tonioo** [comment]
@rjbutler3 Yes, the virtualenv must be enabled before you run this command.
Good point.

**Comment by rjbutler3** [comment]
(env) root@xxxxxxxxx:/srv/modoboa/instance# python manage.py migrate_from_postfixadmin -s crypt
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/models.py", line 89, in <module>
    class DomainAdmins(models.Model):
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/models.py", line 90, in DomainAdmins
    username = models.ForeignKey(Admin, db_column='username')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
(env) root@xxxxxxxx:/srv/modoboa/instance#

**Comment by tonioo** [comment]
@rjbutler3 Looks like the script needs a little refresh. I'll try to fix that this week.

**Comment by tonioo** [comment]
I've released a new version (1.1.2), could you try it?

**Comment by rjbutler3** [comment]
Solved a few issues.

In the settings.py file

Changed the “ENGINE”
Added “HOST” parameter

    "pfxadmin" : {
        "ENGINE" : "django.db.backends.mysql",
        "NAME" : "mail",
        "USER" : "mailadmin",
        "PASSWORD" : "xxxxxxxxxxxxxxxxxxx",
        "HOST" : "xxx.xxx.xxx.xxx",
    },

Ran into an issue with SSL;

Error: (2026, 'SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol')

On the new mail server, made edits to /etc/ssl/openssl.cnf, as described here;

https://www.stefanproell.at/posts/2020-08-18-ubuntu20-04-01-mysql5.6/

I ran the script;

python manage.py migrate_from_postfixadmin -s md5crypt

The script appeared to run, but ended with errors.

When I accessed Modoboa, nothing had migrated.

Here is a snippet from the console;

Migrating domain xxxxxxxxxxxx.net
        Migrating domain aliases
        Migrating mailboxes
        Migrating mailbox aliases
        Migrating administrators

Migrating domain xxxxxxxxx.com
        Migrating domain aliases
        Migrating mailboxes
Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'xxxxxxxx@xxxxxxxx.com' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 290, in handle
    self._do_migration(options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 282, in _do_migration
    self._migrate_domain(pf_domain, options, creator)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 198, in _migrate_domain
    self._migrate_mailboxes(newdom, options, creator)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 178, in _migrate_mailboxes
    new_user.save(creator=creator, using=options["_to"])
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa/core/models.py", line 296, in save
    super(User, self).save(*args, **kwargs)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/modoboa/env/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxxxxxxx@xxxxxxxx.com' for key 'username'")
(env) $

Robert

PS: This is a new Modoboa installation.  Are all of the "Domains" supposed to be created before running the migration script?

**Comment by tonioo** [comment]
@rjbutler3 No, everething should be migrated by the script from what I remember, I'll look into it.
And about your python stack trace, looks like there is a duplicate account in your old server... Can you check that please?

**Comment by tonioo** [comment]
@rjbutler3 Actually the script starts a DB transaction at the very begining so if you encounter any DB issue (like in your case), the whole transaction will be rolled back.

**Comment by rjbutler3** [comment]
@tonioo  I am looking into the duplicate username entry/entries in our DB.  Provided that we are able to get this script working, when run, does the script "copy" the data, leaving the original data intact,  or does the script "remove" the data from the original server once the migration has been completed?

**Comment by tonioo** [comment]
@rjbutler3 This script does not remove anything from the original database.

**Comment by rjbutler3** [comment]
@tonioo  Regarding  django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxxxxxxx@xxxxxxxx.com' for key 'username'")  The user in question is a member of at least 2 domains in which the same email address is used for the username.  Could this be responsible for the error?  In none of our domains does the user have more than 1 username per domain entry in the DB.

**Comment by tonioo** [comment]
@rjbutler3 If the email address is the same, then yes this is the cause.

**Comment by rjbutler3** [comment]
@tonioo  I have a user who has accounts in at least 2 domains, and uses the same email address as his username in both.  If I am unable to change this, what can be done so that the Error: (1062, "Duplicate entry 'xxxxxxxx@xxxxxxxx.com' for key 'username'") does not stop the migration from completing?  What code can I comment out, or what must I change so that the logic looks at both the "domain" AND "username", instead of just the "username"?  Another option might be to have the "Duplicate" "username" changed to a default value, which can be searched and manually corrected post migration.

**Comment by rjbutler3** [comment]
Good day Antoine!  Any feedback on my last post?  Any new ideas?  :-)

**Comment by rjbutler3** [comment]
@tonioo  Good day Antoine! Any feedback on my last post? Any new ideas? :-)

**Comment by tonioo** [comment]
@rjbutler3 Modoboa does not allow two accounts with the same username. So, the only solution I see in order to keep all accounts, is to assign an automatic username to every account that already exists (using a counter for example), or maybe update the username and set it to the email address.
Anyway, it requires to modify the import script and I don't have a lot of time right now...

**Comment by rjbutler3** [comment]
@tonioo  Thank you for your help, and for Modoboa, a wonderfully designed application.  I appreciate the time that you have graciously offered to help me complete this project.  I know what it’s like to not have enough time.  We all have our priorities, and it is not fair to make my priorities yours.  I value your time.  Could you give me an estimate of the cost to modify the script to ignore the duplicate entries and move forward with the import process?  Cleaning up the Modoboa accounts post migration might be messy, but I would rather do that than start all over again with a different email solution.  Thanks again for all your help.

**Comment by rjbutler3** [comment]
@tonioo   I archived the email of the user the script claimed as a duplicate, and deleted their email account.  The script almost completed.  The script now has an issue with “Migrating super administrators”.  There are 3 “super administrators” on our instance of Postfix Admin.  Here is the error;

Migrating super administrators

Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 290, in handle
    self._do_migration(options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 285, in _do_migration
    self._migrate_admins(options, creator, "ALL")
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 220, in _migrate_admins
    old_admin = old_permission.username
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = self.get_object(instance)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 145, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
modoboa_pfxadmin_migrate.models.DoesNotExist: Admin matching query does not exist.
(env) $

**Comment by tonioo** [comment]
@rjbutler3 Looks like you have an entry in postffixadmin domain_admins table which is not linked to an admin...

**Comment by rjbutler3** [comment]
@tonioo  I was able to find and remove the DB entry in postffixadmin domain_admins table which was not linked to an admin.  The migration script ran to completion.  Thank you very much for your help.  I have one issue remaining.  While the script did a masterful job at replicating all of the domains and accounts, it did not migrate the existing email messages.  I am not certain if the script was supposed to migrate the messages as well.  Please confirm.  If not than that is okay.  I have been told that I can use Rsync to move the message data between servers.  Would you recommend this, or a different method to move the message data?

**Comment by tonioo** [comment]
@rjbutler3 This script is not supposed to move emails. You can use rsync if dovecot was already in use on the old server and using the maildir format.

**Comment by rjbutler3** [comment]
@tonioo  Thank you Antoine!  I will be closing this issue later today.  You have been very helpful.
One more question.  The script migrated one domain that I don’t need.  It is very big.  When I try to delete it I get and error after a short time.  I am guessing that this may be a time-out issue.  Is there a way to delete the domain from the command-line using manage.py?  Or a way to extend the timeout to permit the deletion of large domains?

**Comment by tonioo** [comment]
@rjbutler3 What do you mean by large domain?
There is no command line way to delete a domain, unfortunately. The only way would be to do it using python code...

**Comment by rjbutler3** [comment]
@tonioo  Regarding the large domain I was unable to delete.  After repeated efforts, it finally deleted!  I was also able to use Rsync to copy the email message data.  I still have more testing to do, but things are looking good!  Thank you!

**Comment by rjbutler3** [comment]
@tonioo  Good day Antoine!  When I deleted one of the domains that the modoboa-pfxadmin-migrate script migrated, I noticed that the identities belonging to that domain were not deleted.  Rather than having to delete them one-by-one, is there no other way to mass-delete identities belonging to a domain?

**Comment by rjbutler3** [comment]
https://github.com/modoboa/modoboa/issues/379
"actually this is an intended behaviour. Accounts are preserved unless you activate the AUTO_ACCOUNT_REMOVAL option."

I activated this.  Still accounts are not removed when I delete domains.  The above post is from 2013.  Is this still a problem, or am I just missing something?

**Comment by tonioo** [comment]
@rjbutler3 it should work... I've just tried on the official demo site and it works as expected. Do you still see all accounts of the domain, or just some of them?

**Comment by rjbutler3** [comment]
@tonioo  I see all accounts belonging to the domain I just deleted.  I can go to the identities tab and find all the accounts still there.  I can add the domain back, then click on the "view domain's identities" icon, and see all of the accounts belonging to that domain.  Under Modoboa --> Administration tab I have "Automatic account removal" enabled.

**Comment by tonioo** [comment]
@rjbutler3 If you tried you recreate the domain you deleted the first time, it won't work because the link between domain and accounts is not restored. You can't attach an existing account to a new domain...

**Comment by rjbutler3** [comment]
@tonioo  I understand.  Is the only recourse to run SQL queries to remove the accounts left behind after deleting the domain?

**Comment by rjbutler3** [comment]
@tonioo  I am going to start with a clean slate, and conduct the Modoboa installation and migration from scratch.  Perhaps I missed something.  I can't move forward with the current installation due to not being able to delete un-needed domains and the accounts they contain.  I don't know what further damage could be done by directly editing the DB.  I will close this "issue" and my evaluation in a few days.  Thanks for your help.
