### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by fpiccinali** [modoboa/modoboa-pfxadmin-migrate#4]
I try to install mpfxadmin-migrate and it fails.

I am using the modoboa virtual machine.

Logged as root.

cd /root
pip install modoboa-pfxadmin-migrate
![screen2](https://cloud.githubusercontent.com/assets/9351145/11115716/ca267826-892d-11e5-88e8-2972f571a04d.png)

Here is the log : 

```
root@modoboa:~# more /root/.pip/pip.log 
------------------------------------------------------------
/usr/bin/pip run on Thu Nov 12 02:14:23 2015
Downloading/unpacking modoboa-pfxadmin-migrate
  Getting page http://pypi.python.org/simple/modoboa-pfxadmin-migrate
  Could not fetch URL http://pypi.python.org/simple/modoboa-pfxadmin-migrate: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/modoboa-pfxadmin-migrate when looking for download links for modoboa-pfxadmin-migrate
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for modoboa-pfxadmin-migrate:
  * http://pypi.python.org/simple/modoboa-pfxadmin-migrate/
  Getting page http://pypi.python.org/simple/modoboa-pfxadmin-migrate/
  Could not fetch URL http://pypi.python.org/simple/modoboa-pfxadmin-migrate/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/modoboa-pfxadmin-migrate/ when looking for download links for modoboa-pfxadmin-migrate
  Could not find any downloads that satisfy the requirement modoboa-pfxadmin-migrate
No distributions at all found for modoboa-pfxadmin-migrate
Exception information:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/pip/basecommand.py", line 120, in main
    self.run(options, args)
  File "/usr/lib/pymodules/python2.6/pip/commands/install.py", line 161, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/pymodules/python2.6/pip/req.py", line 872, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/pymodules/python2.6/pip/index.py", line 116, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for modoboa-pfxadmin-migrate

```

of course, network is working. I can ping pypi.python.org

**Comment by tonioo** [comment]
Looks like I forgot to upload this package on PyPI... Please use the git version instead.
