### ISSUE TITLE
AttributeError: 'User' object has no attribute 'group'

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa-pfxadmin-migrate#7]
Using Postfixadmin v3 and Modoboa from a pip install, the script starts importing domains and then give this error:
```python
Migrating domain xxx.com
	Migrating domain aliases
	Migrating mailboxes
	Migrating mailbox aliases
	Migrating administrators
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 288, in handle
    self._do_migration(options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 278, in _do_migration
    self._migrate_domain(pf_domain, options, creator)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 199, in _migrate_domain
    self._migrate_admins(options, creator, pf_domain, newdom)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_pfxadmin_migrate/management/commands/migrate_from_postfixadmin.py", line 235, in _migrate_admins
    if "SimpleUsers" == user.group:
AttributeError: 'User' object has no attribute 'group'```

Previously imported domains and mailboxes don't show up in Modoboa web admin.

**Comment by tonioo** [comment]
Duplicates #6. I just pushed a new release (1.0.2) on PyPI.
